data-ezscrex="false" data-cfasync="false" data-pagespeed-no-defer type='text/javascript'>var __ez_gcb="gcb=195-0&cb=144";"use strict";window.googletag=window.googletag||{};googletag.cmd=googletag.cmd||[];__ez.fads=window.__ez.fads||{cmd:[],initslots:{},kvStore:{},divs:[[],[],[],[],[],[],[]],divsd:[],fadcount:0,isJIT:true,};var ez_ad_units=ez_ad_units||[];var ezslots=[];var ezrpos=[];var ezsrqt={};var __ez_fad_haspo=false;var __ez_fad_hascp=false;if(typeof PerformanceObserver!=='undefined'&&typeof PerformanceObserver.supportedEntryTypes!=='undefined'){if(PerformanceObserver.supportedEntryTypes.indexOf('largest-contentful-paint')>-1){__ez_fad_haspo=true;}}
try{var __ez_fad_po=new PerformanceObserver(function(){window.__ez_fad_hascp=true;__ez.fads.cmd.push(function(){__ez.fads.__ez_fad_hascp=true;});});__ez_fad_po.observe({type:'largest-contentful-paint',buffered:true});}catch(e){console.log(e);}
if(typeof __ez_fad_position=='undefined'){function __ez_fad_position(id){if(typeof __ez!="undefined"&&typeof __ez.fads!="undefined"&&typeof __ez.fads.cmd!="undefined"){__ez.fads.cmd.push(function(){__ez.fads.__ez_fad_position(id);});}}}
function ezSetTargetingFromMap(slot,obj){if(typeof slot==='undefined'){return;}
for(var key in obj){if(!obj.hasOwnProperty(key)){continue;}
slot.setTargeting(key,obj[key]);}}
function ezSetSlotTargeting(divid,key,value){var slot=ezGetSlotById(divid);if(slot){slot.setTargeting(key,value);}else{if(typeof __ez.fads.kvStore[divid]==='undefined'){__ez.fads.kvStore[divid]={};}
__ez.fads.kvStore[divid][key]=value;}}
function ezGetSlotById(id){if(typeof window.ezslots==='undefined'||window.ezslots==0){return;}
for(var i=0;i<window.ezslots.length;i++){var slot=window[ezslots[i]];if(typeof slot==='undefined'){continue;}
var slotId=slot.getSlotElementId();if(typeof slotId!=='undefined'&&slotId==id){return slot;}}}
function __ez_close_anchor(){googletag.cmd.push(function(slot){for(var i=0;i<window.ezslots.length;i++){var slot=window[ezslots[i]];if(typeof slot==='undefined'){continue;}
var alS=slot.getTargeting('al')[0]%1000;if(alS==5){googletag.destroySlots([slot]);}}
if(typeof window.ezdomain!=='undefined'){var d=new Date();d.setTime(d.getTime()+(2*60*60*1000));var expires="expires="+d.toGMTString();var cookie="ez_anchor_closed=true;domain=."+ezdomain+';'+expires+"; path=/";document.cookie=cookie;}
if(typeof(__ez_set_outstream_floor)!=='undefined'){__ez_set_outstream_floor(0);}
var anchor=document.getElementById('ezmobfooter');if(!anchor){return;}
anchor.innerHTML='';anchor.style.paddingTop=0;var styleElement=document.getElementById('ezoicCSS');if(!styleElement){return;}
var cert=document.getElementById('ezoic-certification-fixed');if(cert){cert.style.bottom='15px';}
var styles=styleElement.sheet?styleElement.sheet:styleElement.styleSheet;for(var i=0;i<styles.cssRules.length;i++){var rules=styles.cssRules[i];if(rules.selectorText==='body'&&rules.style.height==='auto'&&(rules.style.paddingTop!==''||rules.style.paddingBottom!=='')){styles.deleteRule(i);}}});}__ez.fads=(__ez.fads&&__ez.fads.loaded===true)?__ez.fads:{cmd:typeof window.__ez.fads!="undefined"?window.__ez.fads.cmd||[]:[],logEnabled:false,doc_ht:0,vp_ht:0,loaded:true,isJIT:true,libraryRoot:'https://go.ezodn.com/porpoiseant/',scrollMonitor:{loaded:false,url:'ezjitscroll.js'},positionMonitor:{loaded:false,url:'ezjitpos.js'},adLoadGAM:{loaded:false,url:'ezadloadgam.js'},adLoadAMZN:{loaded:false,url:'ezadloadamzn.js'},adLoadAS:{loaded:false,url:'ezadloadas.js'},adLoadHB:{loaded:false,url:'ezadloadhb.js'},adFilled:{loaded:false,url:'ezadfilled.js'},incontentSticky:{loaded:false,url:'ezicsticky.js'},libraries:['positionMonitor','scrollMonitor','adLoadGAM','adLoadAMZN','adLoadAS','adLoadHB','incontentSticky','adFilled'],librariesLoading:[],libraryCmds:{},kvStore:typeof window.__ez.fads!="undefined"?window.__ez.fads.kvStore||{}:{},addedDivs:[],floatingAdsShown:false,loadTime:new Date().getTime(),onScreenDelay:0,isInit:false,triggerFloatingOnAdd:false,eligibleRefreshAds:[],onScreenDivs:[],onScreenLoadStatus:0,callGAMOnAuctionComplete:[],initslots:typeof window.__ez.fads!="undefined"?window.__ez.fads.initslots||{}:{},divsd:typeof window.__ez.fads!="undefined"?window.__ez.fads.divsd||[]:[],divsdExt:[],version:1,__ez_fad_haspo:window.__ez_fad_haspo||false,__ez_fad_hascp:window.__ez_fad_hascp||false,init:function(){if(this.isInit){return;}
this.isInit=true;this.doc_ht=this.__ez_fad_docht();this.vp_ht=this.__ez_fad_vpht();if(typeof window.__ez.jitver!='undefined'){this.version=window.__ez.jitver;}
if(this.__ez_fad_scroll()>0){this.handleScroll();}
if(this.cmd.length>0){for(var i=0;i<this.cmd.length;i++){if(typeof this.cmd[i]==='function'){this.cmd[i]();}}}
this.cmd={push:function(f){f();}};this.initalizePositions();if(this.version==10){this.onScreenDelay=500;}
this.initOnScreenFallbacks();},reset:function(){this.loadTime=new Date().getTime();this.divsd=[];this.addedDivs=[];this.callLibrary('positionMonitor','reset');this.callLibrary('scrollMonitor','reset');this.callLibrary('adLoadGAM','reset');this.callLibrary('adLoadAMZN','reset');this.callLibrary('adLoadAS','reset');this.callLibrary('adLoadHB','reset');this.callLibrary('incontentSticky','reset');},loadLibrary:function(url,name){if(this.librariesLoading.indexOf(name)==-1&&typeof this[name]!="undefined"&&this[name].loaded!==true){if(document==null||typeof document.body=='undefined'||document.body==null){setTimeout(function(){__ez.fads.loadLibrary(url,name);},100);return;}
this.librariesLoading.push(name);var script=document.createElement('script');script.src=this.libraryRoot+url+"?"+this.getCacheBustParams();script.async=true;script.onload=function(){__ez.fads.LibraryLoaded(name);};document.body.appendChild(script);}},LibraryLoaded:function(name){if(this.libraries.indexOf(name)==-1){return;}
this[name].loaded=true;if(typeof this[name].init==='function'){this[name].init(this.vp_ht,this.doc_ht,this.version);}
this.runLibraryCmds(name);},runLibraryCmds:function(name){if(typeof this.libraryCmds[name]!=='undefined'){for(var i=0;i<this.libraryCmds[name].length;i++){this.libraryCmds[name][i]();}
this.libraryCmds[name]=[];}},callLibrary:function(name,func,args,skipLibraryLoad){if(typeof args!='undefined'&&typeof args.length=='undefined'){args=[args];}
if(this.libraries.indexOf(name)==-1){return;}
if(typeof this[name]!='undefined'&&this[name].loaded==true&&typeof this[name][func]=='function'){return this[name][func].apply(this[name],args);}else{this.libraryCmds[name]=this.libraryCmds[name]||[];this.libraryCmds[name].push(function(){__ez.fads[name][func].apply(__ez.fads[name],args);});if(skipLibraryLoad!==true){this.loadLibrary(this[name].url,name);}}},__ez_fad_docht:function(){return document.documentElement.scrollHeight},__ez_fad_vpht:function(){if(typeof window.innerHeight!='undefined'){return window.innerHeight;}
if(typeof document.documentElement!='undefined'){return document.documentElement.clientHeight;}
var body=typeof document.body!='undefined'&&document.body!=null?document.body:document.getElementsByTagName('body')[0];var screenHeight=typeof window.screen!='undefined'?window.screen.height:0;return Math.min(body.clientHeight,screenHeight)||0;},__ez_fad_scroll:function(){return window.pageYOffset||(document.documentElement||document.body.parentNode||document.body).scrollTop},getCacheBustParams:function(){if(typeof window.__ez_gcb=='undefined'){var d=new Date();gcb='gcb='+d.getFullYear()+d.getMonth()+d.getDate()+d.getHours();cb='0';return gcb+"&"+cb;}else{return window.__ez_gcb}},initalizePositions:function(){if(typeof window.ez_ad_units=='undefined'){setTimeout(function(){__ez.fads.initalizePositions();},100);return;}
for(var i=0;i<window.ez_ad_units.length;i++){var unit=window.ez_ad_units[i];this.__ez_fad_position('div-gpt-ad-'+unit[6]);}},SetViewportHeight:function(viewportHeight){this.vp_ht=viewportHeight;this.callLibrary('positionMonitor','setViewportHeight',[viewportHeight]);},SetDocumentHeight:function(documentHeight){this.doc_ht=documentHeight;this.callLibrary('positionMonitor','setDocumentHeight',[documentHeight]);},handleScroll:function(){this.callLibrary('scrollMonitor','SetAdLoadFunctions',[this.__ez_fad_load.bind(this)]);this.loadFloatingAds(800);this.callLibrary('incontentSticky','CheckIncontentSticky',[]);},__ez_fad_position:function(id){if(document.getElementById(id)==null){return;}
if(this.addedDivs.indexOf(id)!=-1){return;}
this.callLibrary('positionMonitor','AddDiv',[id,4],true);this.__ez_fad_add(id);if(!this.isFloating(id)&&!this.isPixel(id)&&this.isOnScreen(id)){this.log("intial div on screen",id);}else if(this.onScreenLoadStatus==0){setTimeout(function(){this.loadOnScreenAds();}.bind(this),200);this.onScreenLoadStatus=1;}},initOnScreenFallbacks:function(){setTimeout(function(){if(__ez.fads.onScreenLoadStatus==false){__ez.fads.loadOnScreenAds(true);}},2000);if(this.__ez_fad_rdy()==false){document.addEventListener('DOMContentLoaded',function(){__ez.fads.loadOnScreenAds();}.bind(this));}},loadOnScreenAds:function(force){if(this.onScreenLoadStatus==2){return;}
this.log("start on screen load");var floatAds=window.__ez_fad_floating||[];var divs=this.onScreenDivs.concat(floatAds);divs=divs.filter(function(value,index,self){return self.indexOf(value)===index;});this.log("on screen divs",divs);if(divs.length>0){this.markIdsAsRunGAMOnAuctionComplete(divs);this.onScreenLoadStatus=2;setTimeout(function(){this.loadAdsWaitForExternal(divs);}.bind(this),this.onScreenDelay);}},loadAdsWaitForExternal:function(ids,isInitailLoad){if(this.adLoadHB.loaded==true){var auctionIds=this.adLoadHB.FilterByAuctionEligible(ids);}else{var auctionIds={eligible:ids,notEligible:[],running:[]};}
if(auctionIds.eligible.length>0){this.markIdsAsRunGAMOnAuctionComplete(auctionIds.eligible);this.callExternalBidders(auctionIds.eligible,true);}
if(auctionIds.notEligible.length>0){if(isInitailLoad){this.callLibrary('adLoadGAM','LoadAd',[auctionIds.notEligible]);}else{this.refreshAds(auctionIds.notEligible);}}
if(auctionIds.running.length>0){var loadIds=[];for(var i=0;i<auctionIds.running.length;i++){if(this.isGAMOnAuctionComplete(auctionIds.running[i])==false){loadIds.push(auctionIds.running[i]);}}
if(loadIds.length>0){setTimeout(function(){if(isInitailLoad){this.callLibrary('adLoadGAM','LoadAd',[loadIds]);}else{this.refreshAds(loadIds);}},1000);}}},isOnScreen:function(id){var elem=document.getElementById(id);var isOn=(elem=document.getElementById(id))?elem.getBoundingClientRect().top<window.innerHeight&&elem.getBoundingClientRect().bottom>0&&elem.offsetParent!=null:false;if(isOn||this.isFloating(id)){if(this.onScreenDivs.indexOf(id)==-1){this.onScreenDivs.push(id);}}else{if(this.onScreenDivs.indexOf(id)!=-1){this.onScreenDivs.splice(this.onScreenDivs.indexOf(id),1);}}
return isOn;},LoadAds:function(ids,force,waitForExternal){for(var i=0;i<ids.length;i++){this.LoadAd(ids[i],force,waitForExternal);}},LoadAd:function(id,force,waitForExternal){if(!force&&!this.__ez_fad_rdy()){setTimeout(function(){__ez.fads.LoadAd(id,force,waitForExternal);},50);return;}
if(__ez.fads.divsd.indexOf(id)==-1){this.log("loading ad",id,force,waitForExternal);__ez.fads.divsd.push(id);if(this.handleAdsense(id)){this.removeLoadingIcon(id);return;}
this.loadLibrary(this.adLoadGAM.url,'adLoadGAM');if(waitForExternal==true){this.loadAdsWaitForExternal([id],true);}else{this.callExternalBidders(id);this.callLibrary('adLoadGAM','LoadAd',[id]);}}else if(this.isEligibleAdRefresh(id)){this.refreshAds([id]);}else{}},refreshAds:function(ids){this.log("Calling adLoadGAM RefreshAds",ids);this.callLibrary('adLoadGAM','RefreshAds',[ids]);for(var i=0;i<ids.length;i++){this.removeEligibleAdRefresh(ids[i]);}},removeLoadingIcon:function(id){var adDiv=document.getElementById(id);if(adDiv){adDiv.classList.remove("ezoic-adl");}},isFloating:function(id){if(typeof __ez_fad_floating!='undefined'&&__ez_fad_floating.indexOf(id)!=-1){return true;}
return false;},isPixel:function(id){return id.indexOf('-pixel')!==-1;},callExternalBidders:function(ids,force){if(!Array.isArray(ids)){ids=[ids];}
if(force!==true){var ids=ids.filter(function(id){return __ez.fads.divsdExt.indexOf(id)==-1||__ez.fads.isEligibleAdRefresh(id)==true;});}
if(ids.length==0){this.log("no ids left to call external bidders",ids);return;}
this.divsdExt=this.divsdExt.concat(ids);var br1s=this.getRawSlotsById(ids,'br1');this.log("call external bidders",ids);this.callLibrary('adLoadHB','LoadAd',[ids,0,br1s]);if(typeof window.__ezaps!='undefined'&&window.__ezaps.length>0||typeof __ez_hasamzn!='undefined'&&__ez_hasamzn==true){this.callLibrary('adLoadAMZN','LoadAd',[ids,0,br1s]);}
if(typeof openwrapRefreshSlot==='function'){for(var i=0;i<ids.length;i++){if(this.eligibleRefreshAds.indexOf(ids[i])!=-1){var slot=this.adLoadGAM.GetSlotById(ids[i]);if(typeof slot!='undefined'){this.log("refreshing openwrap",ids[i]);openwrapRefreshSlot(slot);}}}}},SetGAMTargeting:function(id,key,value){this.callLibrary('adLoadGAM','SetTargeting',[id,key,value]);},getRawSlotsById:function(ids,key){var rawSlots={};if(typeof window.ezslots_raw!='undefined'){for(var i=0;i<ids.length;i++){var id=ids[i];var slotId=id.split('div-gpt-ad-')[1].split('-',3).join('-');for(var s in window.ezslots_raw){if(typeof window.ezslots_raw[s].tap!="undefined"&&window.ezslots_raw[s].tap.includes(slotId)){rawSlots[id]=window.ezslots_raw[s];}}}
if(key!=null){for(var k in rawSlots){rawSlots[k]=rawSlots[k][key];}}}
return rawSlots;},AdLoadComplete:function(library,ids){this.log("ad load complete",library,ids);if(library=='adLoadHB'){var loadIds=[];var refreshIds=[];for(var i=0;i<ids.length;i++){if(this.isGAMOnAuctionComplete(ids[i])){if(this.eligibleRefreshAds.indexOf(ids[i])!=-1){refreshIds.push(ids[i]);}else{loadIds.push(ids[i]);}
this.removeGAMOnAuctionComplete(ids[i]);}else{this.log("not calling GAM on auction complete for",ids[i]);}}
this.log("load ids",loadIds,"refresh ids",refreshIds);if(loadIds.length>0){this.callLibrary('adLoadGAM','LoadAd',[loadIds]);}
if(refreshIds.length>0){this.refreshAds(refreshIds);}}},AdFilled:function(id){this.callLibrary('adFilled','AdFilled',[id]);},__ez_fad_load:function(adLoadBounds,force){if(!force&&!this.__ez_fad_rdy()){return;}
if(this.positionMonitor.loaded==false){this.loadLibrary(this.positionMonitor.url,'positionMonitor');setTimeout(function(){__ez.fads.__ez_fad_load(adLoadBounds,force);},50);return;}
var divs=this.positionMonitor.getPositionsSorted();var s=[];var loadIds=[];var externalIds=[];for(var i=0;i<divs.length;i++){if(this.divsd.indexOf(divs[i])!=-1&&this.isEligibleAdRefresh(divs[i])==false){continue;}
if(this.positionMonitor.isInBounds(divs[i][0],adLoadBounds)){loadIds.push(divs[i][0]);}else if(this.positionMonitor.isInBounds(divs[i][0],adLoadBounds,true)){externalIds.push(divs[i][0]);}}
if(this.positionMonitor.isUniversalVideoPlayerInBounds(adLoadBounds)){this.log('video player in bounds');}
if(loadIds.length>0){for(var i=0;i<loadIds.length;i++){this.LoadAd(loadIds[i],force,true);}}
if(externalIds.length>0){this.callExternalBidders(externalIds);}},handleAdsense:function(id){var ezslotName=window.ezslotdivs&&ezslotdivs[id]&&ezslotdivs[id].slot;if(typeof ezslotName!='undefined'){var rawTargeting=window[ezslotName+'_raw'];if(rawTargeting&&rawTargeting['compid']=='1'){if(typeof window.ezasBuild==='function'&&window.ezasBuild(id)){this.log("built adsense on ",id);__ez.fads.divsd.push(id);return true;}
rawTargeting['compid']='0';}}
return false},addEligibleAdRefresh:function(id){if(this.eligibleRefreshAds.indexOf(id)==-1){this.eligibleRefreshAds.push(id);}},removeEligibleAdRefresh:function(id){if(this.eligibleRefreshAds.indexOf(id)!=-1){this.eligibleRefreshAds.splice(this.eligibleRefreshAds.indexOf(id),1);}},isEligibleAdRefresh:function(id){return this.eligibleRefreshAds.indexOf(id)!=-1;},addGAMOnAuctionComplete:function(id){if(this.callGAMOnAuctionComplete.indexOf(id)===-1){this.callGAMOnAuctionComplete.push(id);}},removeGAMOnAuctionComplete:function(id){var index=this.callGAMOnAuctionComplete.indexOf(id);if(index!==-1){this.callGAMOnAuctionComplete.splice(index,1);}},isGAMOnAuctionComplete:function(id){return this.callGAMOnAuctionComplete.indexOf(id)!==-1;},markIdsAsRunGAMOnAuctionComplete:function(ids){for(var i=0;i<ids.length;i++){if(!this.isGAMOnAuctionComplete(ids[i])){this.addGAMOnAuctionComplete(ids[i]);}
if(this.divsd.indexOf(ids[i])==-1){this.divsd.push(ids[i]);}}},RefreshAd:function(id,skipExternal){this.log("refresh ad",id);this.callLibrary('adLoadGAM','resetTargeting',[id]);this.addEligibleAdRefresh(id);if(skipExternal!==true){this.callExternalBidders(id);this.addGAMOnAuctionComplete(id);}else{this.LoadAd(id,true,false);}},ShouldResize:function(id){if(this.isOnScreen(id)){return false;}
return true;},ShouldRefresh:function(id){if(!this.isFloating(id)&&!this.isPixel(id)&&!this.isOnScreen(id)){return false;}
return true;},ShouldBang:function(id){if(!this.isFloating(id)&&!this.isPixel(id)&&this.version!=97){if(!this.isOnScreen(id)&&this.positionMonitor.loaded&&this.scrollMonitor.loaded&&this.positionMonitor.isInBounds(id,this.scrollMonitor.GetAdLoadBounds(),true)==false){this.addEligibleAdRefresh(id);return false;}else{}}
return true;},loadFloatingAds:function(timeout,force){this.log("load floating ads",timeout,force);if(this.__ez_fad_rdy()||force){if(!this.floatingAdsShown&&typeof window.__ez_fad_floating!=='undefined'&&window.__ez_fad_floating.length>0){this.floatingAdsShown=true;setTimeout(function(){window.__ez.fads.callLibrary('adLoadGAM','ShowFloatingAds');},timeout);}else if(!this.floatingAdsShown){this.triggerFloatingOnAdd=true;}}},FloatingAdded:function(){if(this.onScreenLoadStatus==2){this.loadFloatingAds(0,true);}},__ez_fad_add:function(id){if(this.addedDivs.indexOf(id)==-1){this.addedDivs.push(id);}},GetInteractionEvents:function(){return["scroll","mousedown","keydown","touchstart","pointerdown"];},__ez_fad_rdy:function(){if(document.body!==null&&(this.__ez_fad_haspo==false&&this.doc_ht>this.vp_ht||this.__ez_fad_hascp)||document.readyState!="loading"){return true;}else{this.doc_ht=this.__ez_fad_docht();this.vp_ht=this.__ez_fad_vpht();}
return false;},log:function(){if(__ez.fads.logEnabled){let args=Array.from(arguments);args.unshift(new Date().toTimeString().split(" ")[0].split(":").slice(0,3).join(":"));args.unshift('%c🧠 ezjit::');args.splice(1,0,'color: #5FA624;');console.log.apply(console,args);}},};__ez.fads.init();__ez.fads.interactionEvents=__ez.fads.GetInteractionEvents();function __ez_handle_init_scroll(e){__ez.fads.handleScroll();for(var i=0;i<__ez.fads.interactionEvents.length;i++){window.removeEventListener(__ez.fads.interactionEvents[i],__ez_handle_init_scroll);}}
for(var ieIdx=0;ieIdx<__ez.fads.interactionEvents.length;ieIdx++){window.addEventListener(__ez.fads.interactionEvents[ieIdx],__ez_handle_init_scroll);}
function __ez_hb_render(id){setTimeout(function(){window.top.epbjs.renderAd(document,id);},10);}__ez.fads.adLoadGAM=(__ez.fads.adLoadGAM&&__ez.fads.adLoadGAM.loaded===true)?__ez.fads.adLoadGAM:{loaded:true,floatingAdsShown:false,slotsDone:[],slotKV:{},isInit:false,floatingStyleLoaded:false,bangerName:'IL11ILILIIlLLLILILLLLIILLLIIL11111LLILiiLIliLlILlLiiLLIiILL',version:1,refreshTargetingResetParams:{'hb_bidder':'','hb_adid':'','hb_pb':'','hb_opt':'','nam':'','pwtsid':'','pwtbst':'','hb_ssid':'','hb_format':'','hb_rt':'','epb':'','epa':'','epp':'','eps':'','epf':'','amznbid':'','amzniid':'','amznp':'','amznsz':'','r_amznbid':'','r_amzniid':'','r_amznp':''},log:__ez.fads.log,hbAsFloorThreshold:0.75,hbAsFloorCap:10.0,init:function(viewportHeight,documentHeight,version){if(this.isInit){return;}
if(version){this.version=version;}else{this.version=__ez.fads.version;}
this.isInit=true;if(this.version!=4){this.LoadGPT();}
if(this.version==15){this.hbAsFloorThreshold=0.5;}
__ez.fads.LibraryLoaded("adLoadGAM");},reset:function(){this.floatingAdsShown=false;this.slotsDone=[];this.slotKV={}},RefreshAds:function(ids){if(!Array.isArray(ids)){ids=[ids];}
if(typeof window[this.bangerName]!='undefined'){for(var i=0;i<ids.length;i++){var id=ids[i];if(__ez.fads.adLoadHB.loaded===true){__ez.fads.adLoadHB.SetAdBid(id);}
this.adjustFloor(id);this.adjustFloorToExtBid(id);window[this.bangerName].RefreshById(id);}}else{setTimeout(function(){__ez.fads.adLoadGAM.RefreshAds(ids)},100);}},replaceOpenwrapBid:function(slot,hb_bid){var ow_bid=slot.getTargeting('ow_hb_opt')[0];if(typeof ow_bid==='undefined'||ow_bid===''||isNaN(ow_bid)){return false;}
ow_bid=parseFloat(ow_bid);if(ow_bid>hb_bid){this.log("adjustFloorToHBBid: openwrap bid is higher",slot.getSlotElementId(),ow_bid,hb_bid);var targetingParams=slot.getTargetingMap();for(var key in targetingParams){if(key.startsWith('ow_hb_')){var newKey='hb_'+key.slice(6);slot.setTargeting(newKey,targetingParams[key][0]);this.log("adjustFloorToHBBid: setting targeting",slot.getSlotElementId(),newKey,targetingParams[key][0]);}}
return ow_bid;}
return false;},adjustFloor:function(id){if(__ez.fads.adFilled.loaded!==true){this.log("adjustFloor: adFilled not loaded",id);return;}
var percentOfMax=1.0;if(this.version==16){percentOfMax=1.0;}else{return;}
var maxFloor=__ez.fads.adFilled.GetMaxFloor(id,percentOfMax,2);this.log("adjustFloor: max floor",id,maxFloor,percentOfMax);if(maxFloor!==false){var slot=this.GetSlotById(id);var floor=this.getFloor(slot);this.log("adjustFloor: max floor",id,maxFloor,floor);if(floor>maxFloor){this.setFloor(slot,maxFloor);}}},adjustFloorToExtBid:function(id){var bidType='hb';var slot=this.GetSlotById(id);if(slot==null){return;}
var hb_bid=slot.getTargeting('hb_opt')[0];if(typeof hb_bid==='undefined'||hb_bid===''||isNaN(hb_bid)){return;}
hb_bid=parseFloat(hb_bid);var openWebResult=this.replaceOpenwrapBid(slot,hb_bid);if(openWebResult!==false){hb_bid=openWebResult;bidType='ow';}
var floor=this.getFloor(slot);this.log("adjustFloorToHBBid: header bid vs floor!",id,"hb_bid:",hb_bid,"floor:",floor,"cap:",this.hbAsFloorCap,"hb must be more than:",(floor*this.hbAsFloorThreshold));let isForcedBid=false;let hbBidder=slot.getTargeting('hb_bidder')[0];if(hbBidder===new URLSearchParams(window.location.search).get('ez_force_hb_solo')){isForcedBid=true;}
if(hb_bid>(floor*this.hbAsFloorThreshold)||hb_bid>this.hbAsFloorCap||isForcedBid){this.setFloor(slot,hb_bid,bidType);}},getFloor(slot){if(!slot){return 0;}
var floor=parseInt(slot.getTargeting('br1')[0]);if(typeof floor==='undefined'||floor===''||isNaN(floor)){return 0;}
return floor/100;},setFloor(slot,floor,bidType){if(!slot){return;}
var GAMAccount=slot.getTargeting('ga')[0];var formattedFloor=this.formatBid(floor,GAMAccount);if(window.ezoibfh.hasOwnProperty(formattedFloor)){var bidFloorHash=window.ezoibfh[formattedFloor];}
this.log("adjustFloorToHBBid: setting floor for ",slot.getSlotElementId(),floor,formattedFloor,bidFloorHash,slot.getTargeting('hb_rt')[0]);if(typeof bidFloorHash!=='undefined'){slot.setTargeting('br1',formattedFloor);slot.setTargeting('eb_br',bidFloorHash);if(bidType=='ow'){this.log("adjustFloorToHBBid: activating openwrap line item",slot.getSlotElementId());slot.setTargeting('pwtbst','1');slot.setTargeting('nam','');}else if(bidType=='hb'){this.log("adjustFloorToHBBid: activating prebid line item",slot.getSlotElementId());slot.setTargeting('nam','1');slot.setTargeting('pwtbst','');}else{slot.setTargeting('pwtbst','');slot.setTargeting('nam','');}}},LoadAd:function(ids,attempt){if(!Array.isArray(ids)){ids=[ids];}
var idsToDo=[];for(var i=0;i<ids.length;i++){if(this.slotsDone.indexOf(ids[i])==-1){idsToDo.push(ids[i]);}}
ids=idsToDo;if(ids.length<1){return;}
if(attempt<1){attempt=1;}else if(attempt>100){return;}
this.slotsDone=this.slotsDone.concat(ids);googletag.cmd.push(function(){if(googletag.pubadsReady!==true){setTimeout(function(){__ez.fads.adLoadGAM.SlotsNotDone(ids);__ez.fads.adLoadGAM.LoadAd(ids,attempt+1)},100);return;}
var gamSlots=[];for(var i=0;i<ids.length;i++){var id=ids[i];var slot=__ez.fads.adLoadGAM.GetSlotById(id);if(slot==null){if(!__ez.fads.initslots.hasOwnProperty(id)){__ez.fads.log("id does not exist in initslots",id);continue;}
var slot_id=__ez.fads.initslots[id](5);var slot=window[slot_id];}
if(parseInt(slot.getTargeting('al')[0])%1000==5&&!slot.getOutOfPage()){__ez.fads.adLoadGAM.showFloatingStyle();}
if(!slot.getOutOfPage()&&document.getElementById(slot.getSlotElementId())===null){__ez.fads.log("gam slot element isn't on the page",id,slot.getSlotElementId());setTimeout(function(){__ez.fads.adLoadGAM.SlotsNotDone(id);__ez.fads.adLoadGAM.LoadAd(id,attempt+1)},100);continue;}else{googletag.display(slot.getSlotElementId());if(typeof window.ezoResponsiveSizes!='undefined'&&typeof slot!='undefined'&&slot!=null&&slot.getTargeting('al')[0]!='1005'&&slot.getTargeting('al')[0]!='3005'){var sizeString=__ez.fads.adLoadGAM.buildSlotResponsiveSizes(slot.getSlotElementId());if(sizeString!==''){__ez.fads.adLoadGAM.adjustResponsiveDiv(slot.getSlotElementId());slot.defineSizeMapping(sizeString);}}
if(typeof window.__ezWillLoadCnx!=='undefined'&&typeof slot!='undefined'&&slot!=null&&slot.getTargeting('al')[0]=='1039'){__ez.fads.adLoadGAM.loadConnatix(slot);continue;}
if(__ez.fads.adLoadHB.loaded===true){__ez.fads.adLoadHB.SetAdBid(id);}
__ez.fads.adLoadGAM.setQueuedTargeting(id);__ez.fads.adLoadGAM.adjustFloor(id);__ez.fads.adLoadGAM.adjustFloorToExtBid(id);gamSlots.push(slot);}}
__ez.fads.log("initial loading gam slots",ids,gamSlots);if(gamSlots.length>0){googletag.pubads().refresh(gamSlots);}});if(this.floatingAdsShown!==true){setTimeout(window.__ez.fads.loadFloatingAds(0,true),0);}},GetTargeting:function(id,key){var slot=this.GetSlotById(id);if(slot){return slot.getTargeting(key);}
return[];},GetStatSourceId:function(id){var slot=this.GetSlotById(id);if(slot){if(slot.getTargeting('nam')[0]=='1'){return parseInt(slot.getTargeting('hb_ssid')[0]);}else{return 35;}}
return 0;},SlotsNotDone:function(ids){for(var i=0;i<ids.length;i++){var index=this.slotsDone.indexOf(ids[i]);if(index>-1){this.slotsDone.splice(index,1);}}},ShowFloatingAds:function(){if(this.floatingAdsShown===true||typeof __ez_fad_floating==='undefined'||__ez_fad_floating.length<1){return;}
this.floatingAdsShown=true;this.showFloatingStyle();this.LoadAd(__ez_fad_floating);},showFloatingStyle:function(){if(this.floatingStyleLoaded){return;}
this.floatingStyleLoaded=true;var e=document.getElementById('ezmobfooter');if(e!=null){e.classList.add('ezmobtrans');}else{var head=document.head||document.getElementsByTagName('head')[0];var style=document.createElement('style');head.appendChild(style);var css="body > #ezmobfooter{bottom:0px;visibility:visible;}";style.type='text/css';if(style.styleSheet){style.styleSheet.cssText=css;}else{style.appendChild(document.createTextNode(css));}}},loadConnatix:function(slot){window.__ezsbwcmd=window.__ezsbwcmd||[];var sr=[slot];window.__ezsbwcmd.push(function(){if(typeof __ezcnxPlayer==='undefined'||!__ezcnxPlayer.getSize()){googletag.pubads().refresh(sr);}else{__ezcnxPlayer.once('removed',function(){googletag.pubads().refresh(sr);});}});},SetTargeting:function(id,key,value){var slot=this.GetSlotById(id);if(slot){slot.setTargeting(key,value);if(this.slotKV[id]&&this.slotKV[id][key]){delete this.slotKV[id][key];}}else{this.slotKV[id]=this.slotKV[id]||{};this.slotKV[id][key]=value;}},resetTargeting:function(id){var slot=this.GetSlotById(id);if(slot){slot.updateTargetingFromMap(this.refreshTargetingResetParams);}},setQueuedTargeting:function(id){if(this.slotKV[id]){var slot=this.GetSlotById(id);if(slot){for(var key in this.slotKV[id]){slot.setTargeting(key,this.slotKV[id][key]);}}}},GetSlotById:function(n){if(typeof googletag=='undefined'||typeof googletag.pubads!='function'||typeof googletag.pubads().getSlots!='function'){return;}
if(__ez_fad_outofpage&&__ez_fad_outofpage.indexOf(n)>-1){var unitID=n.replace('div-gpt-ad-','');if(unitID.endsWith('-0')){unitID=unitID.substring(0,unitID.length-2);}
return this.getOutOfPageSlotByUnitID(unitID);}
var slots=googletag.pubads().getSlots();for(var i=0;i<slots.length;i++){if(slots[i].getSlotElementId()==n){return slots[i];}}},getOutOfPageSlotByUnitID:function(unitID){var slots=googletag.pubads().getSlots();for(var i=0;i<slots.length;i++){if(slots[i].getOutOfPage()&&slots[i].getSlotElementId().includes(unitID)){return slots[i];}}
return;},LoadGPT:function(){(function(){var isHttps=document.location.protocol=="https:";var scriptTag="script";var src=(isHttps?"https:":"http:")+"//securepubads.g.doubleclick.net/tag/js/gpt.js";if(window.__ezHttpConsent&&window._ez_ab_test&&window._ez_ab_test==='mod265'){window.__ezHttpConsent.setByCat(src,scriptTag,[{async:true}],"select_basic_ads",false);}else{var script=document.createElement(scriptTag);script.async=true;script.type="text/javascript";script.src=src;var firstScript=document.getElementsByTagName(scriptTag)[0];firstScript.parentNode.insertBefore(script,firstScript);}})();},buildSlotResponsiveSizes:function(domID){var gptSizeMapping=googletag.sizeMapping();if(typeof window.ezoResponsiveSizes==='undefined'||typeof window.ezoResponsiveSizes[domID]==='undefined'){return false}
window.ezoResponsiveSizes[domID].responsiveSizes.sort(function(a,b){var largerWidth=a.minWidth>b.minWidth;var equalWidth=a.minWidth===b.minWidth;var largerHeight=a.minHeight>b.minHeight;if(largerWidth)return-1;if(equalWidth&&largerHeight)return-1;return 0;});if(window.ezoResponsiveSizes[domID].responsiveSizes){var hasSizesAtZero=false;for(var sizeIdx=0;sizeIdx<window.ezoResponsiveSizes[domID].responsiveSizes.length;sizeIdx++){var sizeDirective=window.ezoResponsiveSizes[domID].responsiveSizes[sizeIdx];if(sizeDirective.minWidth===0&&sizeDirective.minHeight===0){hasSizesAtZero=true;}
gptSizeMapping.addSize([sizeDirective.minWidth,sizeDirective.minHeight],sizeDirective.sizes);}
if(!hasSizesAtZero){gptSizeMapping.addSize([0,0],[]);}}else{return false;}
var mapping=gptSizeMapping.build();if(mapping.length<1){return false;}else{return mapping;}},adjustResponsiveDiv:function(divID){if(!window.ezoResponsiveSizes||!window.ezoResponsiveSizes[divID]){return;}
var adDiv=document.getElementById(divID);if(!adDiv){return;}
var fillSize=__ez_get_largest_ad_size(divID);if(fillSize.length===0||fillSize[0]===0||fillSize[1]===0){return;}
var orivDivSize=[adDiv.getAttribute('ezaw'),adDiv.getAttribute('ezah')];if(orivDivSize[0]===null||orivDivSize[1]===null){return;}
if(fillSize[0]>=orivDivSize[0]){return;}
var parentDiv=adDiv.parentElement;if(!parentDiv||!parentDiv.classList.contains('ezoic-ad')){return;}
parentDiv.style.minWidth=fillSize[0]+'px';parentDiv.style.width=fillSize[0]+'px';parentDiv.style.maxWidth="100%";adDiv.style.width='';adDiv.style.minWidth=fillSize[0]+'px';},getLargestAdSize:function(slotID){var applicableSizes=[];if(ezoResponsiveSizes[slotID]){var clientWidth=document.documentElement.clientWidth;var clientHeight=document.documentElement.clientHeight;var bestResponsiveFit=null;window.ezoResponsiveSizes[slotID].responsiveSizes.forEach(responsiveSize=>{var appliesToViewport=responsiveSize.minWidth<=clientWidth&&responsiveSize.minHeight<=clientHeight;var betterResponsiveFit=bestResponsiveFit===null||responsiveSize.minWidth>bestResponsiveFit.minWidth||(bestResponsiveFit.minWidth==responsiveSize.minWidth&&responsiveSize.minHeight>bestResponsiveFit.minHeight);if(appliesToViewport&&betterResponsiveFit){bestResponsiveFit=responsiveSize;}});if(bestResponsiveFit!==null){applicableSizes=bestResponsiveFit.sizes;}}
var largestDims=[0,0];applicableSizes.forEach(size=>{if(size[0]>largestDims[0]){largestDims[0]=size[0];}
if(size[1]>largestDims[1]){largestDims[1]=size[1];}});return largestDims;},formatBid:function(e,t){var o=e;return o>300&&(o=300),"2497208"==t||"5302779"==t||""==t?(o=o<=0?0:o<=.5?2*Math.floor(100*o/2+.5):o<=1?10*Math.floor(10*o+.5):o<=3?20*Math.floor(100*o/20+.5):o<=10?50*Math.floor(100*o/50+.5):o<=30?100*Math.floor(100*o/100+.5):o<=50?200*Math.floor(100*o/200+.5):o<=120?500*Math.floor(100*o/500+.5):1e3*Math.floor(100*o/1e3+.5))/100>e&&o>2&&(o-=o<=50?2:o<=100?10:o<=300?20:o<=1e3?50:o<=3e3?100:o<=5e3?500:1e3):(o=o<=0?0:o<=1?10*Math.floor(10*o+.5):o<=3?20*Math.floor(100*o/20+.5):o<=10?50*Math.floor(100*o/50+.5):o<=30?100*Math.floor(100*o/100+.5):o<=50?200*Math.floor(100*o/200+.5):o<=120?500*Math.floor(100*o/500+.5):1e3*Math.floor(100*o/1e3+.5))/100>e&&o>2&&(o-=o<=100?10:o<=300?20:o<=1e3?50:o<=3e3?100:o<=5e3?200:o<=12e3?500:1e3),o}};__ez.fads.adLoadGAM.init();</script><script data-ezscrex="false" data-cfasync="false" data-pagespeed-no-defer type='text/javascript'>window.isEZABL=false;window.ezmadspc=300;window.ezoViewCheck=true;</script><script data-ezscrex="false" data-cfasync="false" data-pagespeed-no-defer type='text/javascript'>window.ezDisableInitialLoad=false;</script><script data-ezscrex="false" data-cfasync="false" data-pagespeed-no-defer type='text/javascript'>window.googletag=window.googletag||{};googletag.cmd=googletag.cmd||[];</script><script data-ezscrex="false" data-cfasync="false" data-pagespeed-no-defer type='text/javascript'>window.ezogetbrkey = function(s){ var k = 'br1';var k2 = 'eb_br';if(window.ezogtk == ""){k='br1u';k2='eb_bru';}else if(window.ezogtk != "NT"){k='br1t';k2='eb_brt';} s.setTargeting('br1', s.getTargeting(k));s.setTargeting('eb_br', s.getTargeting(k2));};googletag.cmd.push(function() {window.ezslot_interstitial = googletag.defineOutOfPageSlot('/1254144,22108676293/online_ide_com-pixel1',googletag.enums.OutOfPageFormat.INTERSTITIAL); if(window.ezslot_interstitial != null) {window.ezslot_interstitial.addService(googletag.pubads()).setTargeting('eb_br', '3530fcb6bcc13dc3c1712eaef7d92700').setTargeting('ezoic', '1').setTargeting('avc', '100').setTargeting('ga', '2497208').setTargeting('ic', '1').setTargeting('d', '336810').setTargeting('reft', 'n').setTargeting('br1', '160').setTargeting('br2', '100').setTargeting('iid1', '989155255051860').setTargeting('bvr', '0').setTargeting('bra', 'mod263').setTargeting('al', '2006').setTargeting('tap', 'online_ide_com-pixel1-989155255051860').setTargeting('ap', '9999');}
			googletag.pubads().enableSingleRequest();googletag.pubads().addEventListener('slotRenderEnded', function(event) { __ez.queue.addFunc("ezbanger", "ezbanger", event, false, ['banger.js'], true, true, false, true); });googletag.pubads().addEventListener('impressionViewable', function(event) { __ez.queue.addFunc("ezvb", "ezvb", event, false, ['banger.js'], true, true, false, true); });googletag.pubads().addEventListener('slotVisibilityChanged', function(event) { __ez.queue.addFunc("ezvt", "ezvt", event, false, ['banger.js'], true, true, false, true); });googletag.pubads().addEventListener('slotResponseReceived', function(event) { __ez.queue.addFunc("ezsr", "ezsr", event, false, ['banger.js'], true, true, false, true); });googletag.pubads().addEventListener('slotRequested', function(e) { window.ezsrqt[e.slot.getSlotElementId()] = Date.now();});googletag.setConfig({adExpansion: {enabled: true}});googletag.pubads().disableInitialLoad();googletag.pubads().enableLazyLoad({fetchMarginPercent: 700, renderMarginPercent: 10, mobileScaling: 1.0});googletag.enableServices();});window.ezoll = false;window.ezoadxnc = '1254144';window.ezoadhb = '160';var ezaxmns={};var ezaucmns={};ezaxmns["div-gpt-ad-online_ide_com-medrectangle-2-0"]=36;ezaxmns["div-gpt-ad-online_ide_com-medrectangle-3-0"]=36;ezaxmns["div-gpt-ad-online_ide_com-box-3-0"]=36;
var __ez_fad_outofpage = [];var __ez_fad_floating = ['div-gpt-ad-online_ide_com-medrectangle-2-0'];if(typeof __ez.fads != 'undefined' && typeof __ez.fads.FloatingAdded == "function"){__ez.fads.FloatingAdded();}
	function __ez_init_slot(bvr, did, slotNum, defineFunc) {
		googletag.cmd.push(function() {
			defineFunc();
			ezrpos[slotNum]=slotNum;
			ezslots.push("ezslot_" + slotNum);
			if(__ez.fads.kvStore[did] !== 'undefined') {
				for (var name in __ez.fads.kvStore[did]) {
					if (!__ez.fads.kvStore.hasOwnProperty(name)) {
						ezSetSlotTargeting(did, name, __ez.fads.kvStore[did][name]);
					}
				}
				__ez.fads.kvStore[did] = {};
			}
		});return "ezslot_" + slotNum;
	}
var ezslot_0_raw = {'a':'1','iid1':'7991626017015937','eid':'7991626017015937','t':'135','d':'336810','t1':'135','pvc':'4','ap':'2100','sap':'2100','a':'|0|','as':'revenue','plat':'2','bra':'mod263','ic':'1','at':'mbf','adr':'399','ezosn':'0','reft':'tf','refs':'30','refa':'0','ga':'2497208','gala':'','rid':'99998','pt':'5','al':'2005','compid':'0','tap':'online_ide_com-medrectangle-2-7991626017015937','eb_br':'33dd523f8e4dda158f0aa99686dda7f2','eba':'1','ebss':[10061,10015,10063,11307],'asau':'4952030191','bv':'15','bvm':'0','bvr':'5','avc':'179','shp':'1','ftsn':'12','ftsng':'12','br1':'6','br2':'4','ezoic':'1','nmau':'0','mau':'0','stl':[63,14,28,4,51,0,88,0,71,30,0,31,901,902,903],'deal1':[17,18,19,20,21,22,23,24,25,26,27,28,29,30,760,761,813,814,815,816,817,818,819,893,899,903,917,918,919,1428,2310,2339,2351,2526,2527,2610,2688,2693,2761,2763,2764,2765,3044,3045,3052,3053,3054,3154,3430,3455,3456,3457,3458,3460,3682,3683,3684,3856,3915,3919,3933,4184,4185,4186,4276,4604,4605,5747,6044,6045,6293,6294,6295,3676,774]}; window.ezslots_raw.push(ezslot_0_raw); window.ezslotdivs['div-gpt-ad-online_ide_com-medrectangle-2-0'] = {slot:'ezslot_0',adunit:'/1254144,22108676293/online_ide_com-medrectangle-2'};__ez.fads.initslots['div-gpt-ad-online_ide_com-medrectangle-2-0'] = function(bvr){
				var defScript = function() {ezslot_0 = googletag.defineSlot('/1254144,22108676293/online_ide_com-medrectangle-2',[320,100],'div-gpt-ad-online_ide_com-medrectangle-2-0').addService(googletag.pubads()).setCollapseEmptyDiv(false);ezSetTargetingFromMap(ezslot_0,ezslot_0_raw);};
				return __ez_init_slot(bvr,'div-gpt-ad-online_ide_com-medrectangle-2-0',0, defScript);
			};var ezslot_1_raw = {'a':'1','iid1':'8783579961055234','eid':'8783579961055234','t':'135','d':'336810','t1':'135','pvc':'4','ap':'2104','sap':'2104','a':'|0|','as':'revenue','plat':'2','bra':'mod263','ic':'1','at':'mbf','adr':'399','ezosn':'1','reft':'tf','refs':'30','refa':'0','ga':'2497208','gala':'','rid':'99998','pt':'21','al':'2021','compid':'0','tap':'online_ide_com-medrectangle-3-8783579961055234','eb_br':'e29f69dd468d31a5514dc9b5587ce757','eba':'1','ebss':[10061,10015,10063,11307],'asau':'4952030191','bv':'14','bvm':'0','bvr':'4','avc':'179','shp':'2','ftsn':'12','ftsng':'12','br1':'16','br2':'8','ezoic':'1','nmau':'0','mau':'0','stl':[63,14,28,4,51,0,88,0,71,30,0,31,901,902,903],'deal1':[17,18,19,20,21,22,23,24,25,26,27,815,899,919,1428,2310,2339,2351,2526,2527,2610,2688,2693,2761,2763,2764,2765,3044,3045,3052,3053,3054,3154,3430,3455,3456,3457,3458,3460,3682,3683,3684,3933,4184,4185,4186,4276,4604,4605,5747,6293,6294,6295,3676,774]}; window.ezslots_raw.push(ezslot_1_raw); window.ezslotdivs['div-gpt-ad-online_ide_com-medrectangle-3-0'] = {slot:'ezslot_1',adunit:'/1254144,22108676293/online_ide_com-medrectangle-3'};__ez.fads.initslots['div-gpt-ad-online_ide_com-medrectangle-3-0'] = function(bvr){
				var defScript = function() {ezslot_1 = googletag.defineSlot('/1254144,22108676293/online_ide_com-medrectangle-3',[250,250],'div-gpt-ad-online_ide_com-medrectangle-3-0').addService(googletag.pubads()).setCollapseEmptyDiv(false);ezSetTargetingFromMap(ezslot_1,ezslot_1_raw);};
				return __ez_init_slot(bvr,'div-gpt-ad-online_ide_com-medrectangle-3-0',1, defScript);
			};var ezslot_2_raw = {'a':'1','iid1':'3437962465033510','eid':'3437962465033510','t':'135','d':'336810','t1':'135','pvc':'4','ap':'2101','sap':'2101','a':'|0|','as':'revenue','plat':'2','bra':'mod263','ic':'1','at':'mbf','adr':'399','ezosn':'2','reft':'tf','refs':'30','refa':'0','ga':'2497208','gala':'','rid':'99998','pt':'2','al':'2002','compid':'0','tap':'online_ide_com-box-3-3437962465033510','eb_br':'e29f69dd468d31a5514dc9b5587ce757','eba':'1','ebss':[10061,10015,10063,11307],'asau':'4952030191','bv':'14','bvm':'0','bvr':'4','avc':'179','shp':'3','ftsn':'12','ftsng':'12','br1':'16','br2':'8','ezoic':'1','nmau':'0','mau':'0','stl':[63,14,28,4,51,0,88,0,71,30,0,31,901,902,903],'deal1':[17,18,19,20,21,22,23,24,25,26,1428,2310,2339,2351,2526,2527,2610,2688,2693,2761,2763,2764,2765,3044,3045,3052,3053,3054,3154,3430,3455,3456,3457,3458,3460,3682,3683,3684,4184,4185,4186,4276,5747,6293,6294,6295,3676,774]}; window.ezslots_raw.push(ezslot_2_raw); window.ezslotdivs['div-gpt-ad-online_ide_com-box-3-0'] = {slot:'ezslot_2',adunit:'/1254144,22108676293/online_ide_com-box-3'};__ez.fads.initslots['div-gpt-ad-online_ide_com-box-3-0'] = function(bvr){
				var defScript = function() {ezslot_2 = googletag.defineSlot('/1254144,22108676293/online_ide_com-box-3',[320,50],'div-gpt-ad-online_ide_com-box-3-0').addService(googletag.pubads()).setCollapseEmptyDiv(false);ezSetTargetingFromMap(ezslot_2,ezslot_2_raw);};
				return __ez_init_slot(bvr,'div-gpt-ad-online_ide_com-box-3-0',2, defScript);
			};</
